apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: orders
spec:
  selector:
    app: inventory-service
  ports:
    - port: 80
      targetPort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: ghcr.io/sprasanna03/inventory-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.orders:9092
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
