apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: orders
spec:
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 8083

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/sprasanna03/payment-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.orders:9092
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
