flowchart LR

subgraph Client
    A[Customer / Admin]
end

subgraph Gateway
    GW[API Gateway (JWT / RBAC)]
end

subgraph Bus
    K[(Kafka)]
end

subgraph Infra
    R[(Redis Cache)]
end

subgraph Databases
    DB1[(Orders DB - Postgres)]
    DB2[(Inventory DB - Postgres)]
    DB3[(Payments DB - Postgres)]
    DB4[(Shipping DB - Postgres)]
    DB5[(Notifications DB - Postgres)]
end

%% Request Flow
A -->|REST| GW -->|/api/orders| ORD[Order Service]

%% Events
ORD -- order.created --> K
K -- inventory.reserved / rejected --> INV[Inventory Service]
INV -- payment.authorized / declined --> PAY[Payment Service]
PAY -- shipping.updated --> SHIP[Shipping Service]
SHIP -- notification.send --> NOTIF[Notification Service]

%% Infra
INV <--> R

%% Databases
ORD --- DB1
INV --- DB2
PAY --- DB3
SHIP --- DB4
NOTIF --- DB5
