name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker images
        run: |
          for s in api-gateway order-service inventory-service payment-service shipping-service notification-service; do
            docker buildx build -f src/$s/Dockerfile -t ghcr.io/${{ github.repository_owner }}/$s:latest src/$s --push
          done
